// Hier kannst du die Reihenfolge, Titel und Bilder ganz einfach ändern.
// Wenn du neue Bilder hinzufügen willst, kopiere sie einfach in den Ordner und lege hier einen neuen Eintrag an!

const galleryImages = [
    { id: 'img_01', src: '01.jpg', year: 'Erinnerung', title: 'Bild 1' },
    { id: 'img_02', src: '02.jpg', year: 'Erinnerung', title: 'Bild 2' },
    { id: 'img_03', src: '03.jpg', year: 'Erinnerung', title: 'Bild 3' },
    { id: 'img_04', src: '04.jpg', year: 'Erinnerung', title: 'Bild 4' },
    { id: 'img_05', src: '05.jpg', year: 'Erinnerung', title: 'Bild 5' },
    { id: 'img_06', src: '06.jpg', year: 'Erinnerung', title: 'Bild 6' },
    { id: 'img_07', src: '07.jpg', year: 'Erinnerung', title: 'Bild 7' },
    { id: 'img_08', src: '08.jpg', year: 'Erinnerung', title: 'Bild 8' },
    { id: 'img_09', src: '09.jpg', year: 'Erinnerung', title: 'Bild 9' },
    { id: 'img_10', src: '10.jpg', year: 'Erinnerung', title: 'Bild 10' },
    { id: 'img_11', src: '11.jpg', year: 'Erinnerung', title: 'Bild 11' },
    { id: 'img_12', src: '12.jpg', year: 'Erinnerung', title: 'Bild 12' },
    { id: 'img_13', src: '13.jpg', year: 'Erinnerung', title: 'Bild 13' },
    { id: 'img_14', src: '14.jpg', year: 'Erinnerung', title: 'Bild 14' },
    { id: 'img_15', src: '15.jpg', year: 'Erinnerung', title: 'Bild 15' },
    { id: 'img_16', src: '16.jpg', year: 'Erinnerung', title: 'Bild 16' },
    { id: 'img_17', src: '17.jpg', year: 'Erinnerung', title: 'Bild 17' },
    { id: 'img_18', src: '18.jpg', year: 'Erinnerung', title: 'Bild 18' },
    { id: 'img_19', src: '19.jpg', year: 'Erinnerung', title: 'Bild 19' },
    { id: 'img_20', src: '20.jpg', year: 'Erinnerung', title: 'Bild 20' },
    { id: 'img_21', src: '21.jpg', year: 'Erinnerung', title: 'Bild 21' },
    { id: 'img_22', src: '22.jpg', year: 'Erinnerung', title: 'Bild 22' },
    { id: 'img_23', src: '23.jpg', year: 'Erinnerung', title: 'Bild 23' },
    { id: 'img_24', src: '24.jpg', year: 'Erinnerung', title: 'Bild 24' },
    { id: 'img_25', src: '25.jpg', year: 'Erinnerung', title: 'Bild 25' },
    { id: 'img_26', src: '26.jpg', year: 'Erinnerung', title: 'Bild 26' },
    { id: 'img_27', src: '27.jpg', year: 'Erinnerung', title: 'Bild 27' },
    { id: 'img_28', src: '28.jpg', year: 'Erinnerung', title: 'Bild 28' },
    { id: 'img_29', src: '29.jpg', year: 'Erinnerung', title: 'Bild 29' },
    { id: 'img_ursula', src: 'ursula.jpg', year: 'Erinnerung', title: 'Ursula' }
];
